Dec update
integrateai/integrateai-samples pull request #10
Opened 2023-12-19 16:54 UTC by shaydchara

2024-01-02 16:16 UTC, xichens requested changes

2024-01-02 16:16 UTC, xichens commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "                                    storage_path=aws_storage_path))\\\n",
Do we want to append the session id to the end of the `storage_path` so that the models are not overwritten every time? e.g., `storage_path = f"{aws_storage_path}/vfl/{vfl_train_session.id}"`

2024-01-02 16:16 UTC, xichens commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "                                    storage_path=aws_storage_path))\\\n",
Note that this is only an issue for VFL, because the models (and also the prediction file below) are saved on the client side, which does not modify the specified `storage_path` by default. When the artifacts are saved on the server side, e.g., for HFL, it uses the [ModelStorage](https://github.com/integrateai/edge/blob/99e21d45348828b7e4fd513f1348560bf6585b0f/iai_flour/src/iai_flour/server/storage.py#L35) object to determine the actual path, which will automatically append `f"{session_type}/{session_id}"` to the specified `storage_path`, see [this line](https://github.com/integrateai/edge/blob/99e21d45348828b7e4fd513f1348560bf6585b0f/iai_flour/src/iai_flour/server/storage.py#L52). Maybe we should write a ticket to make the VFL client behave the same way as the server so that the user doesn't need to include the `session_id` manually?

2024-01-02 16:16 UTC, xichens commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "                                    storage_path=aws_storage_path))\\\n",
same as the above

2024-01-02 16:16 UTC, xichens commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "        storage_path=vfl_predict_active_storage_path))\\\n",
Similar to the models, the prediction file will be overwritten every time since the prediction file path is static. We can do something like
```
vfl_predict_active_storage_path = f's3://{base_aws_bucket}/vfl_predict/active_predictions'
vfl_predict_passive_storage_path = f's3://{base_aws_bucket}/vfl_predict/passive_predictions'

storage_path = f"{vfl_predict_active_storage_path}_{vfl_predict_session.id}.csv"
```
Or change the behaviour and handle the actual file path by us instead of using the specified storage_path directly.

2024-01-02 20:17 UTC, shaydchara commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "                                    storage_path=aws_storage_path))\\\n",
Thanks, Xichen. Where possible, we should make the behaviour consistent, so I think we should file that ticket to make the change.

2024-01-03 17:37 UTC, shaydchara commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "        storage_path=vfl_predict_active_storage_path))\\\n",
So I tried updating this as you suggested, and it failed on this section. Any thoughts as to why?

`presigned_result_urls = vfl_predict_session.prediction_result()

print(vfl_predict_active_storage_path)
df_pred = pd.read_csv(presigned_result_urls.get(vfl_predict_active_storage_path))

df_pred.head()`

2024-01-03 17:40 UTC, shaydchara commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "        storage_path=vfl_predict_active_storage_path))\\\n",
I do get the metrics back just before this block:

`{'session_id': 'abafce6fed','federated_metrics': [{}], 'client_metrics': [{'shay.darrach@integrate.ai:43b7520a3814460ab512806eaf761d2c': {'num_predictions': 3245,'storage_path': 's3://magical-testrun2.integrate.ai/vfl_predict/active_predictions_abafce6fed.csv'}}]}`

2024-01-03 17:45 UTC, xichens commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "        storage_path=vfl_predict_active_storage_path))\\\n",
What does the error traceback say?

2024-01-03 17:48 UTC, xichens commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "        storage_path=vfl_predict_active_storage_path))\\\n",
Oh well I think the issue is you need to change that path in 

pd.read_csv(presigned_result_urls.get(vfl_predict_active_storage_path))

to the modified one too, ie the one with the csv

2024-01-03 20:02 UTC, shaydchara commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "        storage_path=vfl_predict_active_storage_path))\\\n",
got it, that worked, thanks

2024-01-09 15:36 UTC, Mordredi approved these changes

2024-01-09 15:40 UTC, xichens approved these changes

2024-01-09 15:59 UTC, merged