EDGE-3053: Update sample notebooks to show how to use registered dataset
integrateai/integrateai-samples pull request #12
Opened 2024-04-23 20:18 UTC by SanjanaSridhar

2024-04-24 19:23 UTC, shaydchara commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +   ]
Once your dataset is registered, you can use the dataset name instead of passing in the dataset path.

2024-04-24 19:25 UTC, shaydchara commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "# .add_task(iai_tb_aws.hfl(train_dataset_name=\"train_name\", test_dataset_name=\"test_name\", use_gpu=False))\n",
If you are using a registered dataset, use the following pattern to add a client task:

2024-04-24 19:25 UTC, shaydchara commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "# .add_task(iai_tb_aws.vfl_train(train_dataset_name=\"train_name\", test_dataset_name=\"test_name\", batch_size=1024,  client_name=\"active_client\", storage_path = storage_path))\n",
Same as above

2024-04-24 19:27 UTC, shaydchara requested changes

2024-04-24 19:27 UTC, shaydchara commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "storage_path = f\"{aws_storage_path}/vfl/{vfl_train_session.id}\"\n",
Can this go up in the block of defining paths, or does it need to be here?

2024-04-24 19:27 UTC, shaydchara commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "# .add_task(iai_tb_aws.vfl_predict(dataset_name=\"predict_name\", raw_output=True, batch_size=1024,  client_name=\"active_client\", storage_path = storage_path))\n",
Same as above

2024-04-25 15:03 UTC, SanjanaSridhar commented on sample_notebook/integrateai_taskrunner_AWS.ipynb
> +    "storage_path = f\"{aws_storage_path}/vfl/{vfl_train_session.id}\"\n",
I could move it up

2024-04-25 19:25 UTC, shaydchara approved these changes

2024-04-26 15:28 UTC, explizito commented on sample_notebook/integrateai_taskrunner_local_python.ipynb
> +    "This is an example notebook that demonstrates creating taskbuilders and running tasks using an AWS and local task runner. \n",
Should this desc match the title? Something like "running tasks using local python and an AWS taskrunner"? Just for consistency

2024-04-26 17:32 UTC, SanjanaSridhar commented on sample_notebook/integrateai_taskrunner_local_python.ipynb
> +    "This is an example notebook that demonstrates creating taskbuilders and running tasks using an AWS and local task runner. \n",
Yep I will make that change :)

2024-04-26 17:34 UTC, SanjanaSridhar commented on sample_notebook/integrateai_taskrunner_local_python.ipynb
> +    "This is an example notebook that demonstrates creating taskbuilders and running tasks using an AWS and local task runner. \n",
I do have this as the title already:
integrate.ai API Sample Notebook to run tasks with local python and an aws taskrunner.

2024-04-26 17:34 UTC, merged