Adding AWS taskrunner notebook
integrateai/integrateai-samples pull request #3
Opened 2023-07-19 14:39 UTC by shaydchara

2023-07-19 14:50 UTC, snazzer requested changes

2023-07-19 14:50 UTC, snazzer commented on sample_notebook/integrateai_taskrunner.ipynb
> +    "IAI_TOKEN = \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lciI6Im1hZ2ljYWwiLCJlbWFpbCI6InNoYXkuZGFycmFjaEBpbnRlZ3JhdGUuYWkiLCJyZWFsbSI6ImlmbCIsInJvbGUiOiJhZG1pbiIsImVudiI6InByb2QiLCJ0b2tlbl9
Remove the token

2023-07-19 18:30 UTC, shaydchara commented on sample_notebook/integrateai_taskrunner.ipynb
> +    "IAI_TOKEN = \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lciI6Im1hZ2ljYWwiLCJlbWFpbCI6InNoYXkuZGFycmFjaEBpbnRlZ3JhdGUuYWkiLCJyZWFsbSI6ImlmbCIsInJvbGUiOiJhZG1pbiIsImVudiI6InByb2QiLCJ0b2tlbl9
Done.

2023-07-20 18:00 UTC, snazzer approved these changes

2023-07-21 17:16 UTC, explizito approved these changes

2023-07-21 17:17 UTC, merged